import type { ExpoConfig } from 'expo/config'

// Bundle identifiers — confirm before submitting to App Store or Google Play.
// Current values are provisional for internal distribution builds.
const BUNDLE_ID = 'com.bronzeiq.app'

const config: ExpoConfig = {
  name: 'Bronze IQ',
  slug: 'bronze-iq',
  owner: 'enriquecerrolaza',
  // User-facing version string shown in the App Store / TestFlight.
  // iOS buildNumber is auto-incremented by EAS (eas.json → build.production.autoIncrement).
  version: '1.0.0',
  // scheme is used for deep links (e.g. OAuth callbacks). Must be unique.
  scheme: 'bronzeiq',
  platforms: ['ios', 'android'],
  orientation: 'portrait',
  userInterfaceStyle: 'light',
  icon: './assets/icon.png',
  ios: {
    supportsTablet: false,
    bundleIdentifier: BUNDLE_ID,
    // infoPlist entries for permission usage descriptions (required by App Store review).
    // Only declare permissions that are actually requested at runtime.
    infoPlist: {
      NSLocationWhenInUseUsageDescription:
        'Bronze IQ usa tu ubicación para mostrarte el índice UV real de tu zona.',
    },
  },
  android: {
    package: BUNDLE_ID,
    adaptiveIcon: {
      foregroundImage: './assets/android-icon-foreground.png',
      monochromeImage: './assets/android-icon-monochrome.png',
      backgroundColor: '#FAF5EE',
    },
    permissions: ['ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION'],
  },
  experiments: {
    typedRoutes: true,
  },
  plugins: [
    // expo-dev-client must be listed first so the native dev launcher is built
    // correctly when running `eas build --profile development`.
    'expo-dev-client',
    'expo-router',
    'expo-secure-store',
    'expo-font',
    [
      'expo-location',
      {
        locationWhenInUsePermission:
          'Bronze IQ usa tu ubicación para mostrarte el índice UV real de tu zona.',
      },
    ],
    [
      'expo-notifications',
      {
        icon: './assets/icon.png',
        color: '#C4996A',
        defaultChannel: 'default',
      },
    ],
    [
      'expo-splash-screen',
      {
        image: './assets/splash-icon.png',
        resizeMode: 'contain',
        backgroundColor: '#FAF5EE',
      },
    ],
  ],
  // Links this project to EAS (Expo Application Services) for cloud builds.
  // projectId is generated by `eas init`; it is not a secret.
  extra: {
    eas: { projectId: '46a29597-c73a-4633-b954-934c88ab6c8e' },
  },
}

export default config
