// Bronze IQ — Database Types
//
// MANUAL TYPES — not yet generated by Supabase CLI.
// These mirror the SQL schema in supabase/migrations/20260525000000_initial_schema.sql.
// When Supabase CLI is configured, replace this file with:
//   npx supabase gen types typescript --local > src/types/database.types.ts
//
// Column names are snake_case (as in PostgreSQL).
// Domain types in src/modules/ use camelCase.
// Mapping between the two happens in repository/service layers (not yet built).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          alias: string
          main_goal: string
          sun_sensitivity: string
          skin_type: number | null
          onboarding_completed: boolean
          disclaimer_accepted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          alias: string
          main_goal: string
          sun_sensitivity: string
          skin_type?: number | null
          onboarding_completed?: boolean
          disclaimer_accepted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          alias?: string
          main_goal?: string
          sun_sensitivity?: string
          skin_type?: number | null
          onboarding_completed?: boolean
          disclaimer_accepted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      exposure_sessions: {
        Row: {
          id: string
          user_id: string
          session_date: string
          duration_minutes: number
          context: string
          uv_index_manual: number | null
          protection_level: string
          sensation_after: string
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          session_date: string
          duration_minutes: number
          context: string
          uv_index_manual?: number | null
          protection_level?: string
          sensation_after: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          session_date?: string
          duration_minutes?: number
          context?: string
          uv_index_manual?: number | null
          protection_level?: string
          sensation_after?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      deletion_requests: {
        Row: {
          id: string
          user_id: string
          requested_at: string
          status: string
          processed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          requested_at?: string
          status?: string
          processed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          requested_at?: string
          status?: string
          processed_at?: string | null
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

// ── Convenience helpers (mirrors Supabase CLI generated helpers) ───────────────

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Inserts<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type Updates<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
